### ISSUE TITLE
mounting issue

### ISSUE THREAD

**Issue by yunmanger1** [toscanini/maestro#10]
I am starting a rabbitmq with this template:

```
templates:
  rabbitmq: 
    base_image: rabbitmq
    mount:
      "/path/to/mount/rabbitmq/data": "/var/lib/rabbitmq"
      "/path/to/mount/rabbitmq/log": "/var/log/rabbitmq"
    config:
      command: /usr/sbin/rabbitmq-server
      ports: 
        - '5672:5672'
        - '15672:15672'
      detach: true
```

but mounting is not done for some reason.

`docker inspect container_id` says:

```
    [{
        "ID": "422137c296a46216704d788427d91fc1fdf792d411ddb55e2a42700a47801f17",
        "Created": "2013-10-14T00:05:55.880300832+06:00",
        "Path": "/usr/sbin/rabbitmq-server",
        "Args": [],
        "Config": {
            "Domainname": "",
            "User": "",
            "Memory": 0,
            "MemorySwap": 0,
            "CpuShares": 0,
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "PortSpecs": [
                "5672:5672",
                "15672:15672"
            ],
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "HOME=/",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "DEBIAN_FRONTEND=noninteractive"
            ],
            "Cmd": [
                "/usr/sbin/rabbitmq-server"
            ],
            "Dns": null,
            "Image": "0d589e879b69",
            "Volumes": null,
            "VolumesFrom": "",
            "WorkingDir": "",
            "Entrypoint": null,
            "NetworkDisabled": false,
            "Privileged": false
        },
        "State": {
            "Running": true,
            "Pid": 9721,
            "ExitCode": 0,
            "StartedAt": "2013-10-14T00:05:55.945071973+06:00",
            "Ghost": false
        },
        "Image": "0d589e879b69e512220b08ff2956af562a347e89aa7067594f0e69cd9f53d4b7",
        "NetworkSettings": {
            "IPAddress": "172.17.0.176",
            "IPPrefixLen": 16,
            "Gateway": "172.17.42.1",
            "Bridge": "docker0",
            "PortMapping": {
                "Tcp": {
                    "15672": "15672",
                    "5672": "5672"
                },
                "Udp": {}
            }
        },
        "SysInitPath": "/usr/bin/docker",
        "ResolvConfPath": "/var/lib/docker/containers/422137c296a46216704d788427d91fc1fdf792d411ddb55e2a42700a47801f17/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/422137c296a46216704d788427d91fc1fdf792d411ddb55e2a42700a47801f17/hostname",
        "HostsPath": "/var/lib/docker/containers/422137c296a46216704d788427d91fc1fdf792d411ddb55e2a42700a47801f17/hosts",
        "Volumes": {},
        "VolumesRW": {}
    }]
```
